-- MySQL Script generated by MySQL Workbench
-- Wed May 30 18:15:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hmis2018
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hmis2018
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hmis2018` DEFAULT CHARACTER SET utf8 ;
USE `hmis2018` ;

-- -----------------------------------------------------
-- Table `hmis2018`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hmis2018`.`Usuario` (
  `email` VARCHAR(120) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `rol` ENUM('admin', 'usuario') NOT NULL DEFAULT 'usuario',
  `password` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `fechaCreacion` DATE NOT NULL,
  `fechaUltimoAcceso` DATE NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
